Class main{
    public static void main (String[]
    args) {}
    System.out.println
    ("Inicializando....");
    System.out.println("Car...");
    Car car = new Car("AMQ123", new
    Account("Andres loiza",
    "AND1235","andresl@hotmail.com",
    "12365"));
    car.passenger = 4;
    car.printDAtaCar();

    System.out.println("Uberx...");
    Uber uberx = new Uberx
    ("MKL185",new Account("Maria",
    "Loloya","JKL12365",
    "maria@hotmail.com", "123478"
    "Toyota","Corolla");
    
}